### ISSUE TITLE
Issuing credential from other credential

### ISSUE THREAD

**Issue by vssnake** [microsoft/entra-verifiedid-wallet-library-android#54]
In the android library is not implemented to issue credential from another credential. Testing the Microsoft Authenticator it works correctly.

Looking at the source code I found that it is not implemented in the [requirements](https://github.com/microsoft/entra-verifiedid-wallet-library-android/blob/dev/walletlibrary/src/main/java/com/microsoft/walletlibrary/mappings/issuance/IssuanceResponseMapping.kt).
```

internal fun IssuanceResponse.addRequirements(requirement: Requirement) {
    when (requirement) {
        is SelfAttestedClaimRequirement -> addSelfAttestedClaimRequirement(requirement)
        is IdTokenRequirement -> addIdTokenRequirement(requirement)
        is AccessTokenRequirement -> addAccessTokenRequirement(requirement)
        is PinRequirement -> addPinRequirement(requirement)
        is GroupRequirement -> addGroupRequirement(requirement)
        is VerifiedIdRequirement -> addVerifiedIdRequirement(requirement)
    }
}
```

**Comment by symorton** [comment]
The functionality is available in the Authenticator App, and we will be adding this functionality to the library by the end of the month.

**Comment by vssnake** [comment]
Thanks for the info. We look foward to
